name: test

on:
  push:
    branches: master
      docs/zh/*.md

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        name: changed-files
        uses: knu/changed-files@v1.0.0
      - name: translate
        uses: chenxizhang/gpt-translator@v1
        with:
          openai_api_key: ${{secrets.OPENAI_API_KEY}}
          files: ${{steps.changed-files.outputs.changed_files_json}}
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
