name: test

on:
  push:
    branches: master
    paths:
      - "docs/zh/*.md"

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: translate
        uses: chenxizhang/gpt-translator@master
        with:
          openai_api_key: ${{secrets.OPENAI_API_KEY_AZURE}}
          files: docs/zh/*.md
          from_language: zh
          to_language: en
          useAzure: true
          commit: false
          endpoint: ${{secrets.OPENAI_API_AZURE_ENDPOINT}}
          modelOrdeployment: gpt-4-turbo
