name: test

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        name: changed-files
        uses: knu/changed-files@v1.0.0
        with:
          paths: docs/zh/*.md
      - name: Translate to English
        shell: pwsh
        env:
          files: ${{steps.changed-files.outputs.changed_files_json}}
          prompt: You have me to translate the content to English, in professional style.You mustn't change the content structure and anything else, you just translate the content based on your language skill.
        run: |
          Set-PSRepository -InstallationPolicy Trusted -Name PSGallery
          Install-Module -Name code365scripts.openai
          Import-Module code365scripts.openai
          $env:files | ConvertFrom-Json | ForEach-Object { 
            if($_ -like "*.md"){
              $content = Get-Content $_; 
              $file = $_ -replace "zh", "en";
              New-Item -Path $file -ItemType File -Force;
              $content | Out-File $file -Force;
              # chat -system $env:prompt -prompt $content | Out-File $file;
            }
          }
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
