name: test

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        name: changed-files
        uses: knu/changed-files@v1.0.0
        with:
          paths: /docs/zh/*.md
      - name: Translate to English
        shell: pwsh
        env:
          files: ${{steps.changed-files.outputs.changed_files}}
        run: |
          ${files}| ForEach-Object {
            $path = $_
            Write-Verbose $path
            $path | Out-File out.txt -Append -Force
          }
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
