name: test

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: changed-files
        uses: knu/changed-files@v1.0.0
        with:
          paths: /docs/zh/*.md
      - name: Translate to English
        shell: pwsh
        run: |
          $changedFiles = ${{steps.changed-files.outputs.files}}
          $changedFiles | ForEach-Object {
            $path = $_
            $content = Get-Content $path
            Write-Host "Translating $path"
            Write-Host $content
          }
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
