name: test

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        shell: pwsh
        run: |
          $PSVersionTable
          Install-Module -Name code365scripts.openai
