name: test

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        name: changed-files
        uses: knu/changed-files@v1.0.0
        with:
          paths: docs/zh/*.md
      - name: Translate to English
        shell: pwsh
        env:
          files: ${{steps.changed-files.outputs.changed_files}}
          prompt: "You have me to translate the content to English, in professional style.You mustn't change the content structure and anything else, you just translate the content based on your language skill."
        run: |
          $env:files -split "`r`n" | ForEach-Object {
            $path = $_
            $content = Get-Content -Path $path
            $file = $path -replace 'zh', 'en'
            New-Item -Path $file -ItemType File -Force
            chat -system $env:prompt -prompt $content | Out-File -FilePath $file
          }
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
